
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'setup_dbt2'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'materialize_tables'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  setup_dbt2:
    appointments:
      appointments_staging:
        +materialized: table
      appointments_final:
        +materialized: table
        +pre-hook: 
          - "delete from `dbt_fivetran.appointments_materialized_dbt` where id in (select id from `dbt_fivetran.appointments_temp_dbt`)"
          - "delete from `dbt_fivetran.appointments_materialized_dbt` where id in (select id from `core_prod_public.appointments` where _fivetran_deleted)"
        +post-hook:
          - "drop table `dbt_fivetran.appointments_temp_dbt`"
          - "drop table `dbt_fivetran.addresses`"
          - "drop table `dbt_fivetran.items`"

    appointments_incremental:
      appointments_staging_incremental:
        +materialized: table
      appointments_final_incremental:
        +materialized: incremental
        +pre-hook: 
          - "delete from `dbt_fivetran.appointments_materialized_dbt_incremental` where id in (select id from `dbt_fivetran.appointments_temp_dbt_incremental`)"
          - "delete from `dbt_fivetran.appointments_materialized_dbt_incremental` where id in (select id from `core_prod_public.appointments` where _fivetran_deleted)"
        +post-hook:
          - "drop table `dbt_fivetran.appointments_temp_dbt_incremental`"
          - "drop table `dbt_fivetran.addresses_incremental`"
          - "drop table `dbt_fivetran.items_incremental`"

    fulfillment_orders:
      fulfillment_orders_staging:
        +materialized: table
      fulfillment_orders_final:
        +materialized: table
        +pre-hook:
          - "delete from `dbt_fivetran.fulfillment_orders_materialized_dbt` where id in (select id from `dbt_fivetran.fulfillment_orders_temp_dbt`)"
          - "delete from `dbt_fivetran.fulfillment_orders_materialized_dbt` where id in (select id from `core_prod_public.fulfillment_orders` where _fivetran_deleted or deleted_at is not null)"
        +post-hook:
          - "drop table `dbt_fivetran.fulfillment_orders_temp_dbt`"
          - "drop table `dbt_fivetran.order_items`"
          - "drop table `dbt_fivetran.shipment_tags`"
          - "drop table `dbt_fivetran.ikea_location_types`"
          - "drop table `dbt_fivetran.order_position`"

    fulfillment_orders_incremental:
      fulfillment_orders_staging_incremental:
        +materialized: table
      fulfillment_orders_final_incremental:
        +materialized: incremental
        +pre-hook:
          - "delete from `dbt_fivetran.fulfillment_orders_materialized_dbt_incremental` where id in (select id from `dbt_fivetran.fulfillment_orders_temp_dbt_incremental`)"
          - "delete from `dbt_fivetran.fulfillment_orders_materialized_dbt_incremental` where id in (select id from `core_prod_public.fulfillment_orders` where _fivetran_deleted or deleted_at is not null)"
        +post-hook:
          - "drop table `dbt_fivetran.fulfillment_orders_temp_dbt_incremental`"
          - "drop table `dbt_fivetran.order_items_incremental`"
          - "drop table `dbt_fivetran.shipment_tags_incremental`"
          - "drop table `dbt_fivetran.ikea_location_types_incremental`"
          - "drop table `dbt_fivetran.order_position_incremental`"
      
    fulfillment_shipments:
      fulfillment_shipments_staging:
        +materialized: table
      fulfillment_shipments_final:
        +materialized: table
        +pre-hook:
          - "delete from `dbt_fivetran.fulfillment_shipments_materialized_dbt` where id in (select id from `dbt_fivetran.fulfillment_shipments_temp_dbt`)"
          - "delete from `dbt_fivetran.fulfillment_shipments_materialized_dbt` where id in (select id from `core_prod_public.logistics_shipments` where _fivetran_deleted or shipping_method_type != 'Logistics::ExternalCarrierShipment')"
        +post-hook:
          - "drop table `dbt_fivetran.fulfillment_shipments_temp_dbt`"  
          - "drop table `dbt_fivetran.packages`"
          - "drop table `dbt_fivetran.shipment_items`"

    fulfillment_shipments_incremental:
      fulfillment_shipments_staging_incremental:
        +materialized: table
      fulfillment_shipments_final_incremental:
        +materialized: incremental
        +pre-hook:
          - "delete from `dbt_fivetran.fulfillment_shipments_materialized_dbt_incremental` where id in (select id from `dbt_fivetran.fulfillment_shipments_temp_dbt_incremental`)"
          - "delete from `dbt_fivetran.fulfillment_shipments_materialized_dbt_incremental` where id in (select id from `core_prod_public.logistics_shipments` where _fivetran_deleted or shipping_method_type != 'Logistics::ExternalCarrierShipment')"
        +post-hook:
          - "drop table `dbt_fivetran.fulfillment_shipments_temp_dbt_incremental`"  
          - "drop table `dbt_fivetran.packages_incremental`"
          - "drop table `dbt_fivetran.shipment_items_incremental`"


    ticket_order_mapping:
      ticket_order_mapping_staging:
        +materialized: table
      ticket_order_mapping_final:
        +materialized: table
        +pre-hook:
          - "delete from `dbt_fivetran.ticket_order_mapping_dbt` where ticket_id in (select ticket_id from `dbt_fivetran.ticket_order_mapping_temp_dbt`)"
        +post-hook:
          - "drop table `dbt_fivetran.tickets_for_order_mapping_temp_dbt`"
          - "drop table `dbt_fivetran.ticket_order_mapping_temp_dbt`"