
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'setup_dbt2'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'materialize_tables'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  setup_dbt2:
    appointments:
      appointments_staging:
        +materialized: table
        +schema: fivetran_esteem_provide_staging
      appointments_final:
        +materialized: table
        +schema: views
        +pre-hook: 
          - "delete from `views.appointments_materialized` where id in (select id from `fivetran_esteem_provide_staging.appointments_temp`)"
          - "delete from `views.appointments_materialized` where id in (select id from `core_prod_public.appointments` where _fivetran_deleted)"
        +post-hook:
          - "drop table `fivetran_esteem_provide_staging.appointments_temp`"
    
    fulfillment_orders:
      fulfillment_orders_staging:
        +materialized: table
        +schema: fivetran_esteem_provide_staging
      fulfillment_orders_final:
        +materialized: table
        +schema: views
        +pre-hook:
          - "delete from `views.fulfillment_orders_materialized` where id in (select id from `fivetran_esteem_provide_staging.fulfillment_orders_temp`)"
          - "delete from `views.fulfillment_orders_materialized` where id in (select id from `core_prod_public.fulfillment_orders` where _fivetran_deleted or deleted_at is not null)"
        +post-hook:
          - "drop table `fivetran_esteem_provide_staging.fulfillment_orders_temp`"
      
    fulfillment_shipments:
      fulfillment_shipments_staging:
        +materialized: table
        +schema: fivetran_esteem_provide_staging
      fulfillment_shipments_final:
        +materialized: table
        +schema: views
        +pre-hook:
          - "delete from `views.fulfillment_shipments_materialized` where id in (select id from `fivetran_esteem_provide_staging.fulfillment_shipments_temp`)"
          - "delete from `views.fulfillment_shipments_materialized` where id in (select id from `core_prod_public.logistics_shipments` where _fivetran_deleted or shipping_method_type != 'Logistics::ExternalCarrierShipment')"
        +post-hook:
          - "drop table `fivetran_esteem_provide_staging.fulfillment_shipments_temp`"  

    ticket_order_mapping:
      ticket_order_mapping_staging:
        +materialized: table
        +schema: zendesk_support
      ticket_order_mapping_intermediate:
        +materialized: table
        +schema: zendesk_support
      ticket_order_mapping_final:
        +materialized: table
        +schema: zendesk_support
        +pre-hook:
          - "delete from `zendesk_support.ticket_order_mapping` where ticket_id in (select ticket_id from `zendesk_support.ticket_order_mapping_temp`)"
        +post-hook:
          - "drop table `zendesk_support.tickets_for_order_mapping_temp`"
          - "drop table `zendesk_support.ticket_order_mapping_temp`"